# Generated by Django 5.2.1 on 2025-05-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='CertificationPractice',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='ChallengeType',
        ),
        migrations.RenameModel(
            old_name='Objective',
            new_name='ContentTypeStatus',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='products',
            new_name='certification_practices',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='skills',
            new_name='challenge_types',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='objectives',
            new_name='content_type_statuses',
        ),
    ]
