# Generated by Django 5.2.1 on 2025-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_product_certificationpractice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContentTypeStatus',
            new_name='ContentType',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content_type_statuses',
            new_name='content_types',
        ),
        migrations.AddField(
            model_name='blog',
            name='statuses',
            field=models.ManyToManyField(blank=True, to='blog.status'),
        ),
    ]
